name: ln_core
description: Ln core components and utilities
version: 1.0.4
repository: https://github.com/orcunoz/ln_core
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.1
  intl: ^0.18.1
  universal_io: ^2.2.2
  url_launcher: ^6.1.11
  flutter_html: ^3.0.0-beta.2
  logger: ^2.0.2+1
  material_color_utilities: ^0.8.0
  stack_trace:

  window_manager: ^0.3.1
  device_info_plus: ^10.0.1
  universal_platform: ^1.0.0+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0

flutter:
  assets:
    - assets/images/
