name: ln_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  universal_io:
  url_launcher: ^6.1.10
  flutter_html: ^3.0.0-beta.2
  logger:
  timelines:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0


flutter:
  assets:
    - assets/images/