name: ln_core
description: Ln core components and utilities
version: 1.0.0
repository: https://github.com/orcunoz/ln_core
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  universal_io: ^2.2.2
  url_launcher: ^6.1.10
  flutter_html: ^3.0.0-beta.2
  logger: ^1.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  assets:
    - assets/images/
